version: "3.7"
services:
  frontend:
    image: frontend-example
    ports:
      - 5000:5000
    depends_on:
      - backend
  backend:
    image: backend-example
    ports:
      - 8000:8000
    environment:
      REDIS: redis-cache
      DB_USERNAME: postgres
      DB_PASSWORD: example
      DB_HOST: db
      FRONT_URL: http://localhost
    depends_on:
      - redis-cache
      - db
  redis-cache:
    image: redis
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./database:/var/lib/postgresql/data
  proxy:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - frontend
      - backend
