FROM ubuntu:16.04

RUN apt-get update && apt-get -y install curl && \
    curl -sL https://deb.nodesource.com/setup_12.x | bash - && \
    apt-get -y install nodejs && \
    apt-get purge -y --auto-remove curl && \
    rm -rf /var/lib/apt/lists/*

COPY . .
RUN npm install
EXPOSE 5000
CMD [ "npm", "start" ]
