version: "3.7"
services:
  frontend:
    image: frontend-example
    ports:
      - 5000:5000
  backend:
    image: backend-example
    ports:
      - 8000:8000
    environment:
      REDIS: redis-cache
      DB_USERNAME: postgres
      DB_PASSWORD: example
      DB_HOST: db
  redis-cache:
    image: redis
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
